// =============================================================================
// error.rs — Error Types for the Hypervisor
// =============================================================================
//
// This module defines a single error enum (HypervisorError) that consolidates
// all possible error types in the project. Using a unified error type lets us
// use the `?` operator throughout the codebase for clean error propagation.
//
// The `thiserror` crate auto-generates `Display` and `Error` trait impls.
// Each variant's #[error("...")] attribute defines its display message.
//
// The `From<T>` impls (both auto-generated by `#[from]` and manual) allow
// automatic conversion from low-level errors (io::Error, KVM errors, etc.)
// into our HypervisorError.
// =============================================================================

use vm_memory::GuestMemoryError;

/// All possible errors that can occur during hypervisor operation.
///
/// This is the central error type. Every module returns `Result<T>` which
/// is an alias for `std::result::Result<T, HypervisorError>`.
#[derive(Debug, thiserror::Error)]
pub enum HypervisorError {
    /// An error from the KVM ioctl layer (e.g., failed to create VM, vCPU, etc.)
    #[error("KVM error: {0}")]
    KvmError(#[from] kvm_ioctls::Error),
    
    /// A standard I/O error from host-side file or socket operations.
    #[error("IO error: {0}")]
    IoError(#[from] std::io::Error),
    
    /// A serialization/deserialization error from bincode (used in snapshots).
    #[error("Bincode error: {0}")]
    BincodeError(#[from] Box<bincode::ErrorKind>),
    
    /// A guest memory operation error (e.g., writing past end of guest RAM).
    /// Wraps a string because GuestMemoryError doesn't implement std::error::Error.
    #[error("Memory error: {0}")]
    MemoryError(String),
    
    /// A virtio queue operation error (e.g., invalid descriptor chain).
    #[error("Virtio error: {0:?}")]
    VirtioError(#[from] virtio_queue::Error),
    
    /// The host CPU architecture is not supported (only x86_64 is supported).
    #[error("Unsupported architecture")]
    UnsupportedArchitecture,
    
    /// A vCPU operation error (e.g., failed to set registers).
    #[error("VCPU error: {0}")]
    VcpuError(String),
    
    /// A snapshot save/restore error.
    #[error("Snapshot error: {0}")]
    SnapshotError(String),
    
    /// Failed to spawn a thread for vCPU execution.
    #[error("Thread spawn error: {0}")]
    ThreadSpawnError(String),
    
    /// A network operation error (e.g., failed to bind socket).
    #[error("Network error: {0}")]
    NetworkError(String),
    
    /// A FAM (Flexible Array Member) operation error from vmm_sys_util.
    /// Used when creating MSR arrays for KVM.
    #[error("FAM error: {0}")]
    FamError(#[from] vmm_sys_util::fam::Error),
    
    /// A catch-all generic error for cases that don't fit other variants.
    #[error("Generic error: {0}")]
    GenericError(String),
}

// --- Manual `From` conversions ---
// These handle error types that need special treatment beyond `#[from]`.

/// Convert a reference to io::Error (needed when we can't move the error)
impl From<&std::io::Error> for HypervisorError {
    fn from(err: &std::io::Error) -> Self {
        HypervisorError::IoError(std::io::Error::new(
            err.kind(),
            err.to_string()
        ))
    }
}

/// Convert from `anyhow::Error` by trying to downcast to known types first.
/// Falls back to GenericError if the inner type isn't recognized.
impl From<anyhow::Error> for HypervisorError {
    fn from(err: anyhow::Error) -> Self {
        // Try to extract the original io::Error if that's what's inside
        if let Some(io_err) = err.downcast_ref::<std::io::Error>() {
            return HypervisorError::IoError(std::io::Error::new(
                io_err.kind(),
                io_err.to_string()
            ));
        }
        HypervisorError::GenericError(err.to_string())
    }
}

/// Convert from GuestMemoryError by wrapping its display string.
/// We can't use `#[from]` because GuestMemoryError may not implement
/// the std::error::Error trait in all vm-memory versions.
impl From<GuestMemoryError> for HypervisorError {
    fn from(err: GuestMemoryError) -> Self {
        HypervisorError::MemoryError(err.to_string())
    }
}

/// Result type alias used throughout the hypervisor.
/// Every function returns `Result<T>` which is `std::result::Result<T, HypervisorError>`.
pub type Result<T> = std::result::Result<T, HypervisorError>;
